CREATE DATABASE CONCESIONARIO;

USE CONCESIONARIO;

CREATE TABLE DELEGACION(
ID_DELEGACION INT NOT NULL AUTO_INCREMENT COMMENT'IDENTIFICADOR DE LA DELEGACION',
LOCALIDAD VARCHAR(100) NOT NULL COMMENT"LOCAILIDAD DE LA DELEGACION",
NUM_TRABAJADORES INT NULL COMMENT"NUMEROS DE LSO TRABAJADORES",
CONSTRAINT PK_DELEGACION PRIMARY KEY (ID_DELEGACION)
);

CREATE TABLE MODELO(
ID_MODELO INT NOT NULL AUTO_INCREMENT COMMENT'Identificador de los modelos',
NUMERO_PUERTAS INT NOT NULL COMMENT'NUMERO DE PUERTAS DE EL MODELO',
POTENCIA INT NOT NULL COMMENT 'POTENCIA DE EL MODELO',
LONGITUD INT NULL COMMENT 'LONGITUD DE EL MODELO',
VELOCCIDAD_PUNTA INT NULL COMMENT'VELOCCIDAD MAXIMA QUE ALCANZA',
CONSTRAINT PK_MODELO PRIMARY KEY (ID_MODELO)
);

CREATE TABLE CLIENTE(
ID_CLIENTE INT NOT NULL AUTO_INCREMENT COMMENT'IDENTIFICADOR DE LOS CLIENTES',
NOMBRE VARCHAR(25) NOT NULL COMMENT 'NOMBRE DE EL CLIENTE',
LOCALIDAD VARCHAR(35) NOT NULL COMMENT'LOCALIDAD DE EL CLIENTE',
EDAD INT NULL COMMENT 'EDAD DE EL CLIENTE',
CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE COCHE(
ID_COCHE INT NOT NULL AUTO_INCREMENT COMMENT'iDENTIFICADOR DE EL COCHE',
ID_MODELO INT NOT NULL COMMENT'IDENTIFICADOR DEL MODELO',
MARCA VARCHAR(40) NOT NULL COMMENT'MARCA DEL COCHE',
CONSTRAINT PK_COCHE PRIMARY KEY (ID_COCHE),
CONSTRAINT FK_COCHE FOREIGN KEY (ID_MODELO) REFERENCES MODELO(ID_MODELO)
);

CREATE TABLE VENDEDOR(
ID_VENDEDOR INT NOT NULL AUTO_INCREMENT COMMENT'IDENTIFICADOR DEL VENDEDOR',
ID_DELEGACION INT NOT NULL COMMENT 'IDENTIFICADOR DE LA DELEGACION',
NOMBRE VARCHAR(25) NOT NULL COMMENT'NOMBRE DE EL VENDEDOR',
APELLIDOS VARCHAR(35) NULL COMMENT 'APELLIDOS DE EL VENDEDOR',
CONSTRAINT PK_VENDEDOR PRIMARY KEY (ID_VENDEDOR),
CONSTRAINT FK_VENDEDOR FOREIGN KEY (ID_DELEGACION) REFERENCES DELEGACION(ID_DELEGACION)
);

CREATE TABLE DIRECTOR(
ID_DIRECTOR INT NOT NULL AUTO_INCREMENT COMMENT 'IDENTIFICADOR DE EL DORIECTOR',
ID_VENDEDOR INT NOT NULL COMMENT 'IDENTIFICADOR DEL VENDEDOR',
NOMBRE VARCHAR(30) NOT NULL COMMENT 'NOMBRE DE EL DIRECTOR',
APELLIDOS VARCHAR(45) NOT NULL COMMENT 'APELLIDOS DEL DIRECTOR',
EDAD INT NOT NULL COMMENT 'EDAD DEL DIRECTOR',
SEXO INT NULL COMMENT 'SEXO DEL DIRECTOR',
CONSTRAINT PK_DIRECTOR PRIMARY KEY (ID_DIRECTOR),
CONSTRAINT FK_DIRECTOR FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDOR(ID_VENDEDOR)
);

CREATE TABLE COMPRA(
ID_COMPRA INT NOT NULL AUTO_INCREMENT COMMENT'IDENTIFICADOR DE LA COMPRA',
ID_VENDEDOR INT NOT NULL COMMENT 'IDENTIFICADOR DEL VENDEDOR',
ID_COCHE INT NOT NULL COMMENT 'IDENTIFICADOR DEL COCHE',
ID_CLIENTE INT NOT NULL COMMENT 'IDENTIFICADOR DEL CLIENTE',
FECHA DATE NULL COMMENT 'FECHA DE COMPRA',
CONSTRAINT PK_COMPRA PRIMARY KEY (ID_COMPRA),
CONSTRAINT FK_COMPRA1 FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDOR(ID_VENDEDOR),
CONSTRAINT FK_COMPRA2 FOREIGN KEY (ID_COCHE) REFERENCES COCHE(ID_COCHE),
CONSTRAINT FK_COMPRA3 FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);